### ISSUE TITLE
Readme for dummies 

### ISSUE THREAD

**Issue by rodakswe** [buffedelic/Heru_mqtt#1]
Hi, any way to update the readme so it suits dummies?
Would love to implement my heru into home assistant but would need some install instructions.

Best regards/Med vänliga hälsningar

**Comment by buffedelic** [comment]
HI

Yeah, the info about the project could shurely be better :)
First off, do you have the required hardware?:

-Modbus enabled controller for your HERU, this is a option that you might ordered when installing or have purchased after.
-USB-rs485 or any device with rs485 capabillity
-Raspberry Pi

**Comment by rodakswe** [comment]
Hi @buffedelic 

Thank you for replying.
Yes, I have the controller with modbus and a spare raspberry pi, I also have the USB to rs485 adapter.
My initial idea was to put the raspberry pi in the attic to avoid running a long cable to my raspberry pi where I host home assistant. 
In the end I decided to run the cable and use the modbus integration directly in home assistant without involving mitt.

Best regards

**Comment by buffedelic** [comment]
Good. I have not checked the modbus implementation in Homeassistant, my code depends on minimalmodbus.
Basically you can redo the code handling connection and reading of the register to suite what ever requirements Homeassistant have for communicating over modbus.

The easy route for you would be to have a standalone unit.
-Pull my repository, preferably in under the path "/home/pi/Heru_mqtt/"
-Have the harware hooked up and functioning
-Open a terminal window in that folder
-run "pip3 -r requirements.txt"
-go to systemd folder in the repository and run "sh deploy.sh"

I can write a more detailed guide in the README in you need it, there are some configuration in heru_link.py that you light need to look at. The constants section on the top

**Comment by buffedelic** [comment]
closing old
